title: Martlet
summary: "Minerva, simplified"
description: "Martlet is a Ruby client for McGill's student portal, Minerva. Minerva sucks, and constantly checking your grades sucks even more."

baseurl: "/martlet/"
url: "http://alexcoco.github.io"
githuburl: "http://github.com/alexcoco/martlet"

version: 0.0.8

markdown: kramdown
